# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@ast-grep/cli-darwin-arm64@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli-darwin-arm64/-/cli-darwin-arm64-0.40.0.tgz";
    hash = "sha512-UehY2MMUkdJbsriP7NKc6+uojrqPn7d1Cl0em+WAkee7Eij81VdyIjRsRxtZSLh440ZWQBHI3PALZ9RkOO8pKQ==";
  };
  "@ast-grep/cli-darwin-x64@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli-darwin-x64/-/cli-darwin-x64-0.40.0.tgz";
    hash = "sha512-RFDJ2ZxUbT0+grntNlOLJx7wa9/ciVCeaVtQpQy8WJJTvXvkY0etl8Qlh2TmO2x2yr+i0Z6aMJi4IG/Yx5ghTQ==";
  };
  "@ast-grep/cli-linux-arm64-gnu@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli-linux-arm64-gnu/-/cli-linux-arm64-gnu-0.40.0.tgz";
    hash = "sha512-4p55gnTQ1mMFCyqjtM7bH9SB9r16mkwXtUcJQGX1YgFG4WD+QG8rC4GwSuNNZcdlYaOQuTWrgUEQ9z5K06UXfg==";
  };
  "@ast-grep/cli-linux-x64-gnu@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli-linux-x64-gnu/-/cli-linux-x64-gnu-0.40.0.tgz";
    hash = "sha512-u2MXFceuwvrO+OQ6zFGoJ6wbATXn46HWwW79j4UPrXYJzVl97jRyjJOIQTJOzTflsk02fjP98DQkfvbXt2dl3Q==";
  };
  "@ast-grep/cli-win32-arm64-msvc@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli-win32-arm64-msvc/-/cli-win32-arm64-msvc-0.40.0.tgz";
    hash = "sha512-E/I1xpF/RQL2fo1CQsQfTxyDLnChsbZ+ERrQHKuF1FI4WrkaPOBibpqda60QgVmUcgOGZyZ/GRb3iKEVWPsQNQ==";
  };
  "@ast-grep/cli-win32-ia32-msvc@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli-win32-ia32-msvc/-/cli-win32-ia32-msvc-0.40.0.tgz";
    hash = "sha512-9h12OQu1BR0GxHEtT+Z4QkJk3LLWLiKwjBkjXUGlASHYDPTyLcs85KwDLeFHs4BwarF8TDdF+KySvB9WPGl/nQ==";
  };
  "@ast-grep/cli-win32-x64-msvc@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli-win32-x64-msvc/-/cli-win32-x64-msvc-0.40.0.tgz";
    hash = "sha512-n2+3WynEWFHhXg6KDgjwWQ0UEtIvqUITFbKEk5cDkUYrzYhg/A6kj0qauPwRbVMoJms49vtsNpLkzzqyunio5g==";
  };
  "@ast-grep/cli@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/cli/-/cli-0.40.0.tgz";
    hash = "sha512-L8AkflsfI2ZP70yIdrwqvjR02ScCuRmM/qNGnJWUkOFck+e6gafNVJ4e4jjGQlEul+dNdBpx36+O2Op629t47A==";
  };
  "@ast-grep/napi-darwin-arm64@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-darwin-arm64/-/napi-darwin-arm64-0.40.0.tgz";
    hash = "sha512-ZMjl5yLhKjxdwbqEEdMizgQdWH2NrWsM6Px+JuGErgCDe6Aedq9yurEPV7veybGdLVJQhOah6htlSflXxjHnYA==";
  };
  "@ast-grep/napi-darwin-x64@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-darwin-x64/-/napi-darwin-x64-0.40.0.tgz";
    hash = "sha512-f9Ol5oQKNRMBkvDtzBK1WiNn2/3eejF2Pn9xwTj7PhXuSFseedOspPYllxQo0gbwUlw/DJqGFTce/jarhR/rBw==";
  };
  "@ast-grep/napi-linux-arm64-gnu@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-linux-arm64-gnu/-/napi-linux-arm64-gnu-0.40.0.tgz";
    hash = "sha512-+tO+VW5GDhT9jGkKOK+3b8+ohKjC98WTzn7wSskd/myyhK3oYL1WTKqCm07WSYBZOJvb3z+WaX+wOUrc4bvtyQ==";
  };
  "@ast-grep/napi-linux-arm64-musl@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-linux-arm64-musl/-/napi-linux-arm64-musl-0.40.0.tgz";
    hash = "sha512-MS9qalLRjUnF2PCzuTKTvCMVSORYHxxe3Qa0+SSaVULsXRBmuy5C/b1FeWwMFnwNnC0uie3VDet31Zujwi8q6A==";
  };
  "@ast-grep/napi-linux-x64-gnu@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-linux-x64-gnu/-/napi-linux-x64-gnu-0.40.0.tgz";
    hash = "sha512-BeHZVMNXhM3WV3XE2yghO0fRxhMOt8BTN972p5piYEQUvKeSHmS8oeGcs6Ahgx5znBclqqqq37ZfioYANiTqJA==";
  };
  "@ast-grep/napi-linux-x64-musl@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-linux-x64-musl/-/napi-linux-x64-musl-0.40.0.tgz";
    hash = "sha512-rG1YujF7O+lszX8fd5u6qkFTuv4FwHXjWvt1CCvCxXwQLSY96LaCW88oVKg7WoEYQh54y++Fk57F+Wh9Gv9nVQ==";
  };
  "@ast-grep/napi-win32-arm64-msvc@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-win32-arm64-msvc/-/napi-win32-arm64-msvc-0.40.0.tgz";
    hash = "sha512-9SqmnQqd4zTEUk6yx0TuW2ycZZs2+e569O/R0QnhSiQNpgwiJCYOe/yPS0BC9HkiaozQm6jjAcasWpFtz/dp+w==";
  };
  "@ast-grep/napi-win32-ia32-msvc@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-win32-ia32-msvc/-/napi-win32-ia32-msvc-0.40.0.tgz";
    hash = "sha512-0JkdBZi5l9vZhGEO38A1way0LmLRDU5Vos6MXrLIOVkymmzDTDlCdY394J1LMmmsfwWcyJg6J7Yv2dw41MCxDQ==";
  };
  "@ast-grep/napi-win32-x64-msvc@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi-win32-x64-msvc/-/napi-win32-x64-msvc-0.40.0.tgz";
    hash = "sha512-Hk2IwfPqMFGZt5SRxsoWmGLxBXxprow4LRp1eG6V8EEiJCNHxZ9ZiEaIc5bNvMDBjHVSnqZAXT22dROhrcSKQg==";
  };
  "@ast-grep/napi@0.40.0" = fetchurl {
    url = "https://registry.npmjs.org/@ast-grep/napi/-/napi-0.40.0.tgz";
    hash = "sha512-tq6nO/8KwUF/mHuk1ECaAOSOlz2OB/PmygnvprJzyAHGRVzdcffblaOOWe90M9sGz5MAasXoF+PTcayQj9TKKA==";
  };
  "@clack/core@0.5.0" = fetchurl {
    url = "https://registry.npmjs.org/@clack/core/-/core-0.5.0.tgz";
    hash = "sha512-p3y0FIOwaYRUPRcMO7+dlmLh8PSRcrjuTndsiA0WAFbWES0mLZlrjVoBRZ9DzkPFJZG6KGkJmoEAY0ZcVWTkow==";
  };
  "@clack/prompts@0.11.0" = fetchurl {
    url = "https://registry.npmjs.org/@clack/prompts/-/prompts-0.11.0.tgz";
    hash = "sha512-pMN5FcrEw9hUkZA4f+zLlzivQSeQf5dRGJjSUbvVYDLvpKCdQx5OaknvKzgbtXOizhP+SJJJjqEbOe55uKKfAw==";
  };
  "@code-yeongyu/comment-checker@0.7.0" = fetchurl {
    url = "https://registry.npmjs.org/@code-yeongyu/comment-checker/-/comment-checker-0.7.0.tgz";
    hash = "sha512-AOic1jPHY3CpNraOuO87YZHO3uRzm9eLd0wyYYN89/76Ugk2TfdUYJ6El/Oe8fzOnHKiOF0IfBeWRo0IUjrHHg==";
  };
  "@hono/node-server@1.19.9" = fetchurl {
    url = "https://registry.npmjs.org/@hono/node-server/-/node-server-1.19.9.tgz";
    hash = "sha512-vHL6w3ecZsky+8P5MD+eFfaGTyCeOHUIFYMGpQGbrBTSmNNoxv0if69rEZ5giu36weC5saFuznL411gRX7bJDw==";
  };
  "@modelcontextprotocol/sdk@1.26.0" = fetchurl {
    url = "https://registry.npmjs.org/@modelcontextprotocol/sdk/-/sdk-1.26.0.tgz";
    hash = "sha512-Y5RmPncpiDtTXDbLKswIJzTqu2hyBKxTNsgKqKclDbhIgg1wgtf1fRuvxgTnRfcnxtvvgbIEcqUOzZrJ6iSReg==";
  };
  "@opencode-ai/plugin@1.1.19" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/plugin/-/plugin-1.1.19.tgz";
    hash = "sha512-Q6qBEjHb/dJMEw4BUqQxEswTMxCCHUpFMMb6jR8HTTs8X/28XRkKt5pHNPA82GU65IlSoPRph+zd8LReBDN53Q==";
  };
  "@opencode-ai/sdk@1.1.19" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/sdk/-/sdk-1.1.19.tgz";
    hash = "sha512-XhZhFuvlLCqDpvNtUEjOsi/wvFj3YCXb1dySp+OONQRMuHlorNYnNa7P2A2ntKuhRdGT1Xt5na0nFzlUyNw+4A==";
  };
  "@types/js-yaml@4.0.9" = fetchurl {
    url = "https://registry.npmjs.org/@types/js-yaml/-/js-yaml-4.0.9.tgz";
    hash = "sha512-k4MGaQl5TGo/iipqb2UDG2UwjXziSWkh0uysQelTlJpX1qGlpUZYm8PnO4DxG1qBomtJUdYJ6qR6xdIah10JLg==";
  };
  "@types/node@24.10.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-24.10.1.tgz";
    hash = "sha512-GNWcUTRBgIRJD5zj+Tq0fKOJ5XZajIiBroOF0yvj2bSU1WvNdYS/dn9UxwsujGW4JX06dnHyjV2y9rRaybH0iQ==";
  };
  "@types/picomatch@3.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@types/picomatch/-/picomatch-3.0.2.tgz";
    hash = "sha512-n0i8TD3UDB7paoMMxA3Y65vUncFJXjcUf7lQY7YyKGl6031FNjfsLs6pdLFCy2GNFxItPJG8GvvpbZc2skH7WA==";
  };
  "accepts@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/accepts/-/accepts-2.0.0.tgz";
    hash = "sha512-5cvg6CtKwfgdmVqY1WIiXKc3Q1bkRqGLi+2W/6ao+6Y7gu/RCwRuAhGEzh5B4KlszSuTLgZYuqFqo5bImjNKng==";
  };
  "ajv-formats@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/ajv-formats/-/ajv-formats-3.0.1.tgz";
    hash = "sha512-8iUql50EUR+uUcdRQ3HDqa6EVyo3docL8g5WJ3FNcWmu62IbkGUue/pEyLBW8VGKKucTPgqeks4fIU1DA4yowQ==";
  };
  "ajv@8.17.1" = fetchurl {
    url = "https://registry.npmjs.org/ajv/-/ajv-8.17.1.tgz";
    hash = "sha512-B/gBuNg5SiMTrPkC+A2+cW0RszwxYmn6VYxB/inlBStS5nx6xHIt/ehKRhIMhqusl7a8LjQoZnjCs5vhwxOQ1g==";
  };
  "argparse@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
    hash = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
  };
  "body-parser@2.2.1" = fetchurl {
    url = "https://registry.npmjs.org/body-parser/-/body-parser-2.2.1.tgz";
    hash = "sha512-nfDwkulwiZYQIGwxdy0RUmowMhKcFVcYXUU7m4QlKYim1rUtg83xm2yjZ40QjDuc291AJjjeSc9b++AWHSgSHw==";
  };
  "bun-types@1.3.6" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.6.tgz";
    hash = "sha512-OlFwHcnNV99r//9v5IIOgQ9Uk37gZqrNMCcqEaExdkVq3Avwqok1bJFmvGMCkCE0FqzdY8VMOZpfpR3lwI+CsQ==";
  };
  "bytes@3.1.2" = fetchurl {
    url = "https://registry.npmjs.org/bytes/-/bytes-3.1.2.tgz";
    hash = "sha512-/Nf7TyzTx6S3yRJObOAV7956r8cr2+Oj8AC5dt8wSP3BQAoeX58NoHyCU8P8zGkNXStjTSi6fzO6F0pBdcYbEg==";
  };
  "call-bind-apply-helpers@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
    hash = "sha512-Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
  };
  "call-bound@1.0.4" = fetchurl {
    url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
    hash = "sha512-+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
  };
  "commander@14.0.2" = fetchurl {
    url = "https://registry.npmjs.org/commander/-/commander-14.0.2.tgz";
    hash = "sha512-TywoWNNRbhoD0BXs1P3ZEScW8W5iKrnbithIl0YH+uCmBd0QpPOA8yc82DS3BIE5Ma6FnBVUsJ7wVUDz4dvOWQ==";
  };
  "content-disposition@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/content-disposition/-/content-disposition-1.0.1.tgz";
    hash = "sha512-oIXISMynqSqm241k6kcQ5UwttDILMK4BiurCfGEREw6+X9jkkpEe5T9FZaApyLGGOnFuyMWZpdolTXMtvEJ08Q==";
  };
  "content-type@1.0.5" = fetchurl {
    url = "https://registry.npmjs.org/content-type/-/content-type-1.0.5.tgz";
    hash = "sha512-nTjqfcBFEipKdXCv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==";
  };
  "cookie-signature@1.2.2" = fetchurl {
    url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.2.2.tgz";
    hash = "sha512-D76uU73ulSXrD1UXF4KE2TMxVVwhsnCgfAyTg9k8P6KGZjlXKrOLe4dJQKI3Bxi5wjesZoFXJWElNWBjPZMbhg==";
  };
  "cookie@0.7.2" = fetchurl {
    url = "https://registry.npmjs.org/cookie/-/cookie-0.7.2.tgz";
    hash = "sha512-yki5XnKuf750l50uGTllt6kKILY4nQ1eNIQatoXEByZ5dWgnKqbnqmTrBE5B4N7lrMJKQ2ytWMiTO2o0v6Ew/w==";
  };
  "cors@2.8.5" = fetchurl {
    url = "https://registry.npmjs.org/cors/-/cors-2.8.5.tgz";
    hash = "sha512-KIHbLJqu73RGr/hnbrO9uBeixNGuvSQjul/jdFvS/KFSIH1hWVd1ng7zOHx+YrEfInLG7q4n6GHQ9cDtxv/P6g==";
  };
  "cross-spawn@7.0.6" = fetchurl {
    url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
    hash = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
  };
  "debug@4.4.3" = fetchurl {
    url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
    hash = "sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
  };
  "depd@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
    hash = "sha512-g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
  };
  "diff@8.0.3" = fetchurl {
    url = "https://registry.npmjs.org/diff/-/diff-8.0.3.tgz";
    hash = "sha512-qejHi7bcSD4hQAZE0tNAawRK1ZtafHDmMTMkrrIGgSLl7hTnQHmKCeB45xAcbfTqK2zowkM3j3bHt/4b/ARbYQ==";
  };
  "dunder-proto@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
    hash = "sha512-KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
  };
  "ee-first@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
    hash = "sha512-WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==";
  };
  "encodeurl@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/encodeurl/-/encodeurl-2.0.0.tgz";
    hash = "sha512-Q0n9HRi4m6JuGIV1eFlmvJB7ZEVxu93IrMyiMsGC0lrMJMWzRgx6WGquyfQgZVb31vhGgXnfmPNNXmxnOkRBrg==";
  };
  "es-define-property@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
    hash = "sha512-e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
  };
  "es-errors@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
    hash = "sha512-Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
  };
  "es-object-atoms@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz";
    hash = "sha512-FGgH2h8zKNim9ljj7dankFPcICIK9Cp5bm+c2gQSYePhpaG5+esrLODihIorn+Pe6FGJzWhXQotPv73jTaldXA==";
  };
  "escape-html@1.0.3" = fetchurl {
    url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
    hash = "sha512-NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==";
  };
  "etag@1.8.1" = fetchurl {
    url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
    hash = "sha512-aIL5Fx7mawVa300al2BnEE4iNvo1qETxLrPI/o05L7z6go7fCw1J6EQmbK4FmJ2AS7kgVF/KEZWufBfdClMcPg==";
  };
  "eventsource-parser@3.0.6" = fetchurl {
    url = "https://registry.npmjs.org/eventsource-parser/-/eventsource-parser-3.0.6.tgz";
    hash = "sha512-Vo1ab+QXPzZ4tCa8SwIHJFaSzy4R6SHf7BY79rFBDf0idraZWAkYrDjDj8uWaSm3S2TK+hJ7/t1CEmZ7jXw+pg==";
  };
  "eventsource@3.0.7" = fetchurl {
    url = "https://registry.npmjs.org/eventsource/-/eventsource-3.0.7.tgz";
    hash = "sha512-CRT1WTyuQoD771GW56XEZFQ/ZoSfWid1alKGDYMmkt2yl8UXrVR4pspqWNEcqKvVIzg6PAltWjxcSSPrboA4iA==";
  };
  "express-rate-limit@8.2.1" = fetchurl {
    url = "https://registry.npmjs.org/express-rate-limit/-/express-rate-limit-8.2.1.tgz";
    hash = "sha512-PCZEIEIxqwhzw4KF0n7QF4QqruVTcF73O5kFKUnGOyjbCCgizBBiFaYpd/fnBLUMPw/BWw9OsiN7GgrNYr7j6g==";
  };
  "express@5.2.1" = fetchurl {
    url = "https://registry.npmjs.org/express/-/express-5.2.1.tgz";
    hash = "sha512-hIS4idWWai69NezIdRt2xFVofaF4j+6INOpJlVOLDO8zXGpUVEVzIYk12UUi2JzjEzWL3IOAxcTubgz9Po0yXw==";
  };
  "fast-deep-equal@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
    hash = "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
  };
  "fast-uri@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/fast-uri/-/fast-uri-3.1.0.tgz";
    hash = "sha512-iPeeDKJSWf4IEOasVVrknXpaBV0IApz/gp7S2bb7Z4Lljbl2MGJRqInZiUrQwV16cpzw/D3S5j5Julj/gT52AA==";
  };
  "finalhandler@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/finalhandler/-/finalhandler-2.1.1.tgz";
    hash = "sha512-S8KoZgRZN+a5rNwqTxlZZePjT/4cnm0ROV70LedRHZ0p8u9fRID0hJUZQpkKLzro8LfmC8sx23bY6tVNxv8pQA==";
  };
  "forwarded@0.2.0" = fetchurl {
    url = "https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz";
    hash = "sha512-buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==";
  };
  "fresh@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/fresh/-/fresh-2.0.0.tgz";
    hash = "sha512-Rx/WycZ60HOaqLKAi6cHRKKI7zxWbJ31MhntmtwMoaTeF7XFH9hhBp8vITaMidfljRQ6eYWCKkaTK+ykVJHP2A==";
  };
  "function-bind@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
    hash = "sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
  };
  "get-intrinsic@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz";
    hash = "sha512-9fSjSaos/fRIVIp+xSJlE6lfwhES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==";
  };
  "get-proto@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
    hash = "sha512-sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
  };
  "gopd@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
    hash = "sha512-ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
  };
  "has-symbols@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
    hash = "sha512-1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
  };
  "hasown@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
    hash = "sha512-0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
  };
  "hono@4.12.0" = fetchurl {
    url = "https://registry.npmjs.org/hono/-/hono-4.12.0.tgz";
    hash = "sha512-NekXntS5M94pUfiVZ8oXXK/kkri+5WpX2/Ik+LVsl+uvw+soj4roXIsPqO+XsWrAw20mOzaXOZf3Q7PfB9A/IA==";
  };
  "http-errors@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/http-errors/-/http-errors-2.0.1.tgz";
    hash = "sha512-4FbRdAX+bSdmo4AUFuS0WNiPz8NgFt+r8ThgNWmlrjQjt1Q7ZR9+zTlce2859x4KSXrwIsaeTqDoKQmtP8pLmQ==";
  };
  "iconv-lite@0.7.1" = fetchurl {
    url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.7.1.tgz";
    hash = "sha512-2Tth85cXwGFHfvRgZWszZSvdo+0Xsqmw8k8ZwxScfcBneNUraK+dxRxRm24nszx80Y0TVio8kKLt5sLE7ZCLlw==";
  };
  "inherits@2.0.4" = fetchurl {
    url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
    hash = "sha512-k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
  };
  "ip-address@10.0.1" = fetchurl {
    url = "https://registry.npmjs.org/ip-address/-/ip-address-10.0.1.tgz";
    hash = "sha512-NWv9YLW4PoW2B7xtzaS3NCot75m6nK7Icdv0o3lfMceJVRfSoQwqD4wEH5rLwoKJwUiZ/rfpiVBhnaF0FK4HoA==";
  };
  "ipaddr.js@1.9.1" = fetchurl {
    url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
    hash = "sha512-0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
  };
  "is-promise@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-promise/-/is-promise-4.0.0.tgz";
    hash = "sha512-hvpoI6korhJMnej285dSg6nu1+e6uxs7zG3BYAm5byqDsgJNWwxzM6z6iZiAgQR4TJ30JmBTOwqZUw3WlyH3AQ==";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
  };
  "jose@6.1.3" = fetchurl {
    url = "https://registry.npmjs.org/jose/-/jose-6.1.3.tgz";
    hash = "sha512-0TpaTfihd4QMNwrz/ob2Bp7X04yuxJkjRGi4aKmOqwhov54i6u79oCv7T+C7lo70MKH6BesI3vscD1yb/yzKXQ==";
  };
  "js-yaml@4.1.1" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.1.tgz";
    hash = "sha512-qQKT4zQxXl8lLwBtHMWwaTcGfFOZviOJet3Oy/xmGk2gZH677CJM9EvtfdSkgWcATZhj/55JZ0rmy3myCT5lsA==";
  };
  "json-schema-traverse@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
    hash = "sha512-NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
  };
  "json-schema-typed@8.0.2" = fetchurl {
    url = "https://registry.npmjs.org/json-schema-typed/-/json-schema-typed-8.0.2.tgz";
    hash = "sha512-fQhoXdcvc3V28x7C7BMs4P5+kNlgUURe2jmUT1T//oBRMDrqy1QPelJimwZGo7Hg9VPV3EQV5Bnq4hbFy2vetA==";
  };
  "jsonc-parser@3.3.1" = fetchurl {
    url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz";
    hash = "sha512-HUgH65KyejrUFPvHFPbqOY0rsFip3Bo5wb4ngvdi1EpCYWUQDC5V+Y7mZws+DLkr4M//zQJoanu1SP+87Dv1oQ==";
  };
  "math-intrinsics@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
    hash = "sha512-/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
  };
  "media-typer@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/media-typer/-/media-typer-1.1.0.tgz";
    hash = "sha512-aisnrDP4GNe06UcKFnV5bfMNPBUw4jsLGaWwWfnH3v02GnBuXX2MCVn5RbrWo0j3pczUilYblq7fQ7Nw2t5XKw==";
  };
  "merge-descriptors@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-2.0.0.tgz";
    hash = "sha512-Snk314V5ayFLhp3fkUREub6WtjBfPdCPY1Ln8/8munuLuiYhsABgBVWsozAG+MWMbVEvcdcpbi9R7ww22l9Q3g==";
  };
  "mime-db@1.54.0" = fetchurl {
    url = "https://registry.npmjs.org/mime-db/-/mime-db-1.54.0.tgz";
    hash = "sha512-aU5EJuIN2WDemCcAp2vFBfp/m4EAhWJnUNSSw0ixs7/kXbd6Pg64EmwJkNdFhB8aWt1sH2CTXrLxo/iAGV3oPQ==";
  };
  "mime-types@3.0.2" = fetchurl {
    url = "https://registry.npmjs.org/mime-types/-/mime-types-3.0.2.tgz";
    hash = "sha512-Lbgzdk0h4juoQ9fCKXW4by0UJqj+nOOrI9MJ1sSj4nI8aI2eo1qmvQEie4VD1glsS250n15LsWsYtCugiStS5A==";
  };
  "ms@2.1.3" = fetchurl {
    url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
    hash = "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
  };
  "negotiator@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/negotiator/-/negotiator-1.0.0.tgz";
    hash = "sha512-8Ofs/AUQh8MaEcrlq5xOX0CQ9ypTF5dl78mjlMNfOK08fzpgTHQRQPBxcPlEtIw0yRpws+Zo/3r+5WRby7u3Gg==";
  };
  "object-assign@4.1.1" = fetchurl {
    url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
    hash = "sha512-rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
  };
  "object-inspect@1.13.4" = fetchurl {
    url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.13.4.tgz";
    hash = "sha512-W67iLl4J2EXEGTbfeHCffrjDfitvLANg0UlX3wFUUSTx92KXRFegMHUVgSqE+wvhAbi4WqjGg9czysTV2Epbew==";
  };
  "oh-my-opencode-darwin-arm64@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-darwin-arm64/-/oh-my-opencode-darwin-arm64-3.10.0.tgz";
    hash = "sha512-KQ1Nva4eU03WIaQI8BiEgizYJAeddUIaC8dmks0Ug/2EkH6VyNj41+shI58HFGN9Jlg9Fd6MxpOW92S3JUHjOw==";
  };
  "oh-my-opencode-darwin-x64-baseline@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-darwin-x64-baseline/-/oh-my-opencode-darwin-x64-baseline-3.10.0.tgz";
    hash = "sha512-yOaVd0E1qspT2xP/BMJaJ/rpFTwkOh9U/SAk6uOuxHld6dZGI9e2Oq8F3pSD16xHnnpaz4VzadtT6HkvPdtBYg==";
  };
  "oh-my-opencode-darwin-x64@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-darwin-x64/-/oh-my-opencode-darwin-x64-3.10.0.tgz";
    hash = "sha512-PydZ6wKyLZzikSZA3Q89zKZwFyg0Ouqd/S6zDsf1zzpUWT1t5EcpBtYFwuscD7L4hdkIEFm8wxnnBkz5i6BEiA==";
  };
  "oh-my-opencode-linux-arm64-musl@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-linux-arm64-musl/-/oh-my-opencode-linux-arm64-musl-3.10.0.tgz";
    hash = "sha512-ca61zr+X8q0ipO2x72qU+4R6Dsr168OM9aXI6xDHbrr0l3XZlRO8xuwQidch1vE5QRv2/IJT10KjAFInCERDug==";
  };
  "oh-my-opencode-linux-arm64@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-linux-arm64/-/oh-my-opencode-linux-arm64-3.10.0.tgz";
    hash = "sha512-pLzcPMuzBb1tpVgqMilv7QdsE2xTMLCWT3b807mzjt0302fZTfm6emwymCG25RamHdq7+mI2B0rN7hjvbymFog==";
  };
  "oh-my-opencode-linux-x64-baseline@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-linux-x64-baseline/-/oh-my-opencode-linux-x64-baseline-3.10.0.tgz";
    hash = "sha512-a6OhfqMXhOTq1On8YHRRlVsNtMx84kgNAnStk/sY1Dw0kXU68QK4tWXVF+wNdiRG3egeM2SvjhJ5RhWlr3CCNQ==";
  };
  "oh-my-opencode-linux-x64-musl-baseline@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-linux-x64-musl-baseline/-/oh-my-opencode-linux-x64-musl-baseline-3.10.0.tgz";
    hash = "sha512-UqArUpatMuen8+hZhMSbScaSmJlcwkEtf/IzDN1iYO0CttvhyYMUmm3el/1gWTAcaGNDFNkGmTli5WNYhnm2lA==";
  };
  "oh-my-opencode-linux-x64-musl@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-linux-x64-musl/-/oh-my-opencode-linux-x64-musl-3.10.0.tgz";
    hash = "sha512-lZkoEWwmrlVoZKewHNslUmQ2D6eWi1YqsoZMTd3qRj8V4XI6TDZHxg86hw4oxZ/EnKO4un+r83tb09JAAb1nNQ==";
  };
  "oh-my-opencode-linux-x64@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-linux-x64/-/oh-my-opencode-linux-x64-3.10.0.tgz";
    hash = "sha512-m0Ys8Vnl8jUNRE5/aIseNOF1H57/W77xh3vkyBVfnjzHwQdEUWZz3IdoHaEWIFgIP2+fsNXRHqpx7Pbtuhxo6Q==";
  };
  "oh-my-opencode-windows-x64-baseline@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-windows-x64-baseline/-/oh-my-opencode-windows-x64-baseline-3.10.0.tgz";
    hash = "sha512-BBv+dNPuh9LEuqXUJLXNsvi3vL30zS1qcJuzlq/s8rYHry+VvEVXCRcMm5Vo0CVna8bUZf5U8MDkGDHOAiTeEw==";
  };
  "oh-my-opencode-windows-x64@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/oh-my-opencode-windows-x64/-/oh-my-opencode-windows-x64-3.10.0.tgz";
    hash = "sha512-BivOu1+Yty9N6VSmNzmxROZqjQKu3ImWjooKZDfczvYLDQmZV104QcOKV6bmdOCpHrqQ7cvdbygmeiJeRoYShg==";
  };
  "on-finished@2.4.1" = fetchurl {
    url = "https://registry.npmjs.org/on-finished/-/on-finished-2.4.1.tgz";
    hash = "sha512-oVlzkg3ENAhCk2zdv7IJwd/QUD4z2RxRwpkcGY8psCVcCYZNq4wYnVWALHM+brtuJjePWiYF/ClmuDr8Ch5+kg==";
  };
  "once@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
    hash = "sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
  };
  "parseurl@1.3.3" = fetchurl {
    url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
    hash = "sha512-CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
  };
  "path-key@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
    hash = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
  };
  "path-to-regexp@8.3.0" = fetchurl {
    url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-8.3.0.tgz";
    hash = "sha512-7jdwVIRtsP8MYpdXSwOS0YdD0Du+qOoF/AEPIt88PcCFrZCzx41oxku1jD88hZBwbNUIEfpqvuhjFaMAqMTWnA==";
  };
  "picocolors@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
    hash = "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
  };
  "picomatch@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz";
    hash = "sha512-5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
  };
  "pkce-challenge@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/pkce-challenge/-/pkce-challenge-5.0.1.tgz";
    hash = "sha512-wQ0b/W4Fr01qtpHlqSqspcj3EhBvimsdh0KlHhH8HRZnMsEa0ea2fTULOXOS9ccQr3om+GcGRk4e+isrZWV8qQ==";
  };
  "proxy-addr@2.0.7" = fetchurl {
    url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz";
    hash = "sha512-llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==";
  };
  "qs@6.14.1" = fetchurl {
    url = "https://registry.npmjs.org/qs/-/qs-6.14.1.tgz";
    hash = "sha512-4EK3+xJl8Ts67nLYNwqw/dsFVnCf+qR7RgXSK9jEEm9unao3njwMDdmsdvoKBKHzxd7tCYz5e5M+SnMjdtXGQQ==";
  };
  "range-parser@1.2.1" = fetchurl {
    url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
    hash = "sha512-Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
  };
  "raw-body@3.0.2" = fetchurl {
    url = "https://registry.npmjs.org/raw-body/-/raw-body-3.0.2.tgz";
    hash = "sha512-K5zQjDllxWkf7Z5xJdV0/B0WTNqx6vxG70zJE4N0kBs4LovmEYWJzQGxC9bS9RAKu3bgM40lrd5zoLJ12MQ5BA==";
  };
  "require-from-string@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
    hash = "sha512-Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
  };
  "router@2.2.0" = fetchurl {
    url = "https://registry.npmjs.org/router/-/router-2.2.0.tgz";
    hash = "sha512-nLTrUKm2UyiL7rlhapu/Zl45FwNgkZGaCpZbIHajDYgwlJCOzLSk+cIPAnsEqV955GjILJnKbdQC1nVPz+gAYQ==";
  };
  "safer-buffer@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
    hash = "sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
  };
  "send@1.2.1" = fetchurl {
    url = "https://registry.npmjs.org/send/-/send-1.2.1.tgz";
    hash = "sha512-1gnZf7DFcoIcajTjTwjwuDjzuz4PPcY2StKPlsGAQ1+YH20IRVrBaXSWmdjowTJ6u8Rc01PoYOGHXfP1mYcZNQ==";
  };
  "serve-static@2.2.1" = fetchurl {
    url = "https://registry.npmjs.org/serve-static/-/serve-static-2.2.1.tgz";
    hash = "sha512-xRXBn0pPqQTVQiC8wyQrKs2MOlX24zQ0POGaj0kultvoOCstBQM5yvOhAVSUwOMjQtTvsPWoNCHfPGwaaQJhTw==";
  };
  "setprototypeof@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
    hash = "sha512-E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
  };
  "shebang-command@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
    hash = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
  };
  "shebang-regex@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
    hash = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
  };
  "side-channel-list@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/side-channel-list/-/side-channel-list-1.0.0.tgz";
    hash = "sha512-FCLHtRD/gnpCiCHEiJLOwdmFP+wzCmDEkc9y7NsYxeF4u7Btsn1ZuwgwJGxImImHicJArLP4R0yX4c2KCrMrTA==";
  };
  "side-channel-map@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/side-channel-map/-/side-channel-map-1.0.1.tgz";
    hash = "sha512-VCjCNfgMsby3tTdo02nbjtM/ewra6jPHmpThenkTYh8pG9ucZ/1P8So4u4FGBek/BjpOVsDCMoLA/iuBKIFXRA==";
  };
  "side-channel-weakmap@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/side-channel-weakmap/-/side-channel-weakmap-1.0.2.tgz";
    hash = "sha512-WPS/HvHQTYnHisLo9McqBHOJk2FkHO/tlpvldyrnem4aeQp4hai3gythswg6p01oSoTl58rcpiFAjF2br2Ak2A==";
  };
  "side-channel@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/side-channel/-/side-channel-1.1.0.tgz";
    hash = "sha512-ZX99e6tRweoUXqR+VBrslhda51Nh5MTQwou5tnUDgbtyM0dBgmhEDtWGP/xbKn6hqfPRHujUNwz5fy/wbbhnpw==";
  };
  "sisteransi@1.0.5" = fetchurl {
    url = "https://registry.npmjs.org/sisteransi/-/sisteransi-1.0.5.tgz";
    hash = "sha512-bLGGlR1QxBcynn2d5YmDX4MGjlZvy2MRBDRNHLJ8VI6l6+9FUiyTFNJ0IveOSP0bcXgVDPRcfGqA0pjaqUpfVg==";
  };
  "statuses@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/statuses/-/statuses-2.0.2.tgz";
    hash = "sha512-DvEy55V3DB7uknRo+4iOGT5fP1slR8wQohVdknigZPMpMstaKJQWhwiYBACJE3Ul2pTnATihhBYnRhZQHGBiRw==";
  };
  "toidentifier@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz";
    hash = "sha512-o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==";
  };
  "type-is@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/type-is/-/type-is-2.0.1.tgz";
    hash = "sha512-OZs6gsjF4vMp32qrCbiVSkrFmXtG/AZhY3t0iAMrMBiAZyV9oALtXO8hsrHbMXF9x6L3grlFuwW2oAz7cav+Gw==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@7.16.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.16.0.tgz";
    hash = "sha512-Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==";
  };
  "unpipe@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
    hash = "sha512-pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF7V8NuzeyPNqRksA3hztKQ==";
  };
  "vary@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
    hash = "sha512-BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==";
  };
  "vscode-jsonrpc@8.2.1" = fetchurl {
    url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.1.tgz";
    hash = "sha512-kdjOSJ2lLIn7r1rtrMbbNCHjyMPfRnowdKjBQ+mGq6NAW5QY2bEZC/khaC5OR8svbbjvLEaIXkOq45e2X9BIbQ==";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
  };
  "wrappy@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
    hash = "sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
  };
  "zod-to-json-schema@3.25.1" = fetchurl {
    url = "https://registry.npmjs.org/zod-to-json-schema/-/zod-to-json-schema-3.25.1.tgz";
    hash = "sha512-pM/SU9d3YAggzi6MtR4h7ruuQlqKtad8e9S0fmxcMi+ueAK5Korys/aWcV9LIIHTVbj01NdzxcnXSN+O74ZIVA==";
  };
  "zod@4.1.8" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.8.tgz";
    hash = "sha512-5R1P+WwQqmmMIEACyzSvo4JXHY5WiAFHRMg+zBZKgKS+Q1viRa0C1hmUKtHltoIFKtIdki3pRxkmpP74jnNYHQ==";
  };
}